name: FaintLPUtils
author: zEnderX5_ , Rafael Auler
main: me.rafaelauler.ss.BukkitMain
version: 1.0
loadbefore: [KPCore]
depend: [AuraSkills]
commands:
  membro:
  set-prefix:
  tag:
  pickencantar:
  report:
  adquirirvip:
  
  
  
  