name: ServerController
author: Ebenezer7
main: me.rafaelauler.ss.BukkitMain
version: 1.0
loadbefore: [KPCore, ProtocolLib]
commands:
  set-prefix:
  tag:
  pickencantar:
  report:
  adquirirvip:
  modo:
  sudo:
  consolesudo:
  manutencao:
  ctag:
  dano:
  
  
  
  
  
  
  