name: THE-PIT
author: Rafael Auler
main: me.rafaelauler.minigame.thepit.BukkitMain
version: BUILD-8
softdepend: [KPCore]
api-version: 1.20
commands:
  thepit:
  thepithelp:
  thepiteditmode:
  setthepittopkills:
  updatethepittopkill:
  givegold:
  thepitkickall:
  
  
  
  
  
  
  
